[package]
name = "nsmt-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "NSMT/Yggdrasil 核心：身份、帧协议、错误码"

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
ed25519-dalek.workspace = true
rand_core.workspace = true
machine-uid.workspace = true
hostname.workspace = true
tokio.workspace = true
